### ISSUE TITLE
Forall is well and truly broken

### ISSUE THREAD

**Issue by ekmett** [ekmett/constraints#11]
From Oerjan:

```haskell
{-# LANGUAGE Safe #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE TypeOperators #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE ConstraintKinds #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE ScopedTypeVariables #-}

import Data.Constraint
import Data.Constraint.Forall
import Data.Proxy

type family H a b x y z where
    H a b x x z = a
    H a b x y y = a
    H a b x y x = a
    H a b x y z = b

class (H a b x y z ~ a) => I a b x y z
instance (H a b x y z ~ a) => I a b x y z
class Forall (I a b x y) => J a b x y
instance Forall (I a b x y) => J a b x y
class Forall (J a b x) => K a b x
instance Forall (J a b x) => K a b x

k :: Forall (K a b) :- K a b x
k = inst
k' :: K a b x :- Forall (J a b x)
k' = Sub Dict
j :: Forall (J a b x) :- J a b x y
j = inst
j' :: J a b x y :- Forall (I a b x y)
j' = Sub Dict
i :: Forall (I a b x y) :- I a b x y z
i = inst
h :: I a b x y z :- (H a b x y z ~ a)
h = Sub Dict

a :: Forall (K a b) :- I a b x y z
a = i `trans` j' `trans` j `trans` k' `trans` k

b :: Dict (I a b x y z)
b = case a of
    Sub d -> d

c :: I a b x y z => Proxy (a,b,x,y,z) -> H a b x y z -> a
c _ = id

uc :: forall a b. b -> a
uc = case b :: Dict (I a b () Bool Int) of
    Dict -> c (Proxy :: Proxy (a,b,(),Bool,Int))
```

**Comment by ekmett** [comment]
Oerjan greatly simplified this counter example.

```haskell
{-# LANGUAGE Safe #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE TypeOperators #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE ScopedTypeVariables #-}

import Data.Constraint
import Data.Constraint.Forall
import Data.Proxy

data C

type family H a b x where
    H a b C = b
    H a b x = a

class (H a b x ~ a) => I a b x
instance (H a b x ~ a) => I a b x

b :: Dict (I a b C)
b = case inst :: Forall (I a b) :- I a b x of
    Sub d -> d

c :: I a b x => Proxy (a,b,x) -> H a b x -> a
c _ = id

uc :: forall a b. b -> a
uc = case b :: Dict (I a b C) of
    Dict -> c (Proxy :: Proxy (a,b,C))
```

**Comment by treeowl** [comment]
Can this be closed now?

**Comment by ekmett** [comment]
As soon as I can bring myself to ship it. =)

The new `Forall` is comparatively a _lot_ harder to use.

**Comment by AndrasKovacs** [comment]
I was directed here from this [SO thread](http://stackoverflow.com/questions/33576274/how-to-create-a-polymorphic-unboxed-array-within-st-monad/33576918#33576918). 

After some fiddling I managed to produce the following alternative `Forall` definition:

    import Data.Constraint
    import Data.Constraint.Unsafe

    type family Clog (a :: k) :: j -- Non-exported

    type Forall (p :: k -> Constraint) = p (Clog p)

    inst :: Forall p :- p a
    inst = unsafeCoerceConstraint

This prevents Ørjan's code examples from compiling, but it's still usable, and in particular it works in the case of my linked SO answer. 

My puny mind has so far failed to come up with ways to get unsoundness with the new definition. I'd like some other people to give it a try.

**Comment by oerjan** [comment]
András Kovács and I seem to have had the same idea independently triggered by our Stackoverflow conversation, and I also made [a version](http://oerjan.nvg.org/haskell/Forall/NewForall.hs). It *should* be a drop-in replacement for the version on Hackage (some [test cases](http://oerjan.nvg.org/haskell/Forall/TestNewForall.hs)). However, both our versions seem to trigger a spurious superclass cycle for two of my unsound programs. I pared this down to the following, of which the second fails:

```haskell
class (f a ~ g a) => H f g a
instance (f a ~ g a) => H f g a

class Forall (H f g) => H1 f g
instance Forall (H f g) => H1 f g
```

Note that the type equality seems essential; the otherwise similar `Monoid1` and `Monoid2` test cases work fine. I've reported this as a [GHC bug](https://ghc.haskell.org/trac/ghc/ticket/11067)

(Also, congrats on finally dragging me onto GitHub.)

**Comment by AndrasKovacs** [comment]
I have found that changing the `Forall`-s from type synonyms to closed type families gets rid of the superclass cycle error. In Ørjan's terminology:

    type family Forall (p :: k -> Constraint) where
      Forall p = p (Skolem p)

Also luckily, the old unsound code still doesn't check.

**Comment by treeowl** [comment]
If @oerjan's fix works, I guess `Forall1` and `inst1` can be deprecated. Nice! Two questions:

1. Why the `trans ... refl` rather than the obvious thing? Is there some subtle problem with this?

```haskell
inst = unsafeCoerceConstraint
instF = unsafeCoerceConstraint
instT = unsafeCoerceConstraint
```

2. Definitions closer to the one @AndrasKovacs started with reduces the number of type families needed. That said, @oerjan's versions might be seen as making the intent clearer.

```haskell
type family Skolem (p :: j) :: k
-- SkolemF is replaced by SkolemT1
type family SkolemT1 (p :: i) (f :: j) :: k
type family SkolemT2 (p :: i) (f :: j) :: k
```

**Comment by treeowl** [comment]
I just realized that `Forall` can be defined more generally with @AndrasKovacs's skolems, for whatever it's worth:

```haskell
type family Forall (p :: k -> l) where
  Forall p = p (Skolem p)
```

Then the same `Forall` can be used also to describe types as well as constraints. Whether it's ever useful to do so is another question, since such shenanigans generally aren't needed for types, but here's an example:

```haskell
foof :: forall (p :: k -> *) (a :: *) . Forall p -> p a
foof = unsafeCoerce (\x -> x)
```

**Comment by oerjan** [comment]
Oh, I didn't realize treeowl and dfeuer was the same person :)

The reason I used `trans ... refl` is because I started from the Hackage code and misunderstood `unsafeCoerceConstraint` - I see now that it does `refl` by itself.

Although generalizing the `Skolem` kinds should be harmless, I'm not sure how useful it is, because it's *absolutely essential* that they not be exported or available to the user in any way. And since you seeded my doubts, while away from the computer I realized that `Forall` as defined above still leaks too much. Here's yet another `unsafeCoerce`:

```haskell
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE PolyKinds #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}

import Data.Constraint
import Data.Constraint.Forall -- version with type family Skolem and Forall

type family GetArg x where
    GetArg (p (a :: *)) = a
type GetSkolem p = GetArg (Forall p)

type family Knotted where
    Knotted = GetSkolem Knot
class (a ~ Knotted) => Knot a
instance (a ~ Knotted) => Knot a

fromKnotted :: Knot a => Knotted -> a
fromKnotted = id

toKnotted :: Knot a => a -> Knotted
toKnotted = id

uc :: forall a b. a -> b
uc = case inst of
    Sub (Dict :: Dict (Knot a)) -> case inst of
        Sub (Dict :: Dict (Knot b)) -> fromKnotted . toKnotted
```

I see an "obvious" way to fix this: make `Forall` etc. type classes instead:

```haskell
class p (Skolem p) => Forall (p :: k -> Constraint)
instance p (Skolem p) => Forall (p :: k -> Constraint)
```

Unfortunately, [when I tried this](http://oerjan.nvg.org/haskell/Forall/NewForall2.hs), while the exploit stopped working, the superclass cycles came back, including in `Monoid2` which didn't have them before. I also tried going via a `Forall_` type family as superclass, but it didn't help.

**Comment by oerjan** [comment]
[Fixed it](http://oerjan.nvg.org/haskell/Forall/NewForall3.hs), I just had to switch which of the type class and the type family was outermost.

Now to brace for the next hole...

**Comment by treeowl** [comment]
To keep everything in one place, here's @oerjan's latest version.

```haskell
{- Modified version to use Forall type family + Forall_ type class by Ørjan
 - Johansen -}

{-# LANGUAGE CPP #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE ConstraintKinds #-}
{-# LANGUAGE EmptyDataDecls #-}
{-# LANGUAGE KindSignatures #-}
{-# LANGUAGE TypeOperators #-}
{-# LANGUAGE Trustworthy #-}

{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE PolyKinds #-}
{-# LANGUAGE TypeFamilies #-}

#if defined(__GLASGOW_HASKELL__) && __GLASGOW_HASKELL__ >= 707
{-# LANGUAGE RoleAnnotations #-}
#endif
-----------------------------------------------------------------------------
-- |
-- Module      :  Data.Constraint.Forall
-- Copyright   :  (C) 2011-2013 Edward Kmett,
-- License     :  BSD-style (see the file LICENSE)
--
-- Maintainer  :  Edward Kmett <ekmett@gmail.com>
-- Stability   :  experimental
-- Portability :  non-portable
--
-- This module uses a trick to provide quantification over constraints.
----------------------------------------------------------------------------

module Data.Constraint.Forall
  ( Forall, inst
  , ForallF, instF
  , Forall1, inst1
  , ForallT, instT
  ) where

import Data.Constraint
import Data.Constraint.Unsafe

-- Once GHC supports it, these might be made closed with no instances.
type family Skolem (p :: k -> Constraint) :: k
type family SkolemF (p :: k2 -> Constraint) (f :: k1 -> k2) :: k1
type family SkolemT1 (p :: k3 -> Constraint) (t :: k1 -> k2 -> k3) :: k1
type family SkolemT2 (p :: k3 -> Constraint) (t :: k1 -> k2 -> k3) :: k2

-- | A quantified constraint
-- The outer type family is to prevent GHC from giving a spurious superclass
-- cycle error.
-- The inner class is to prevent the Skolem from leaking to the user, which
-- would be disastrous.
type family Forall (p :: k -> Constraint) where
    Forall p = Forall_ p
class p (Skolem p) => Forall_ (p :: k -> Constraint)
instance p (Skolem p) => Forall_ (p :: k -> Constraint)

type family ForallF (p :: k2 -> Constraint) (f :: k1 -> k2) where
    ForallF p f = ForallF_ p f
class p (f (SkolemF p f)) => ForallF_ (p :: k2 -> Constraint) (f :: k1 -> k2)
instance p (f (SkolemF p f)) => ForallF_ (p :: k2 -> Constraint) (f :: k1 -> k2)

type Forall1 p = Forall p

type family ForallT (p :: k3 -> Constraint) (t :: k1 -> k2 -> k3) where
    ForallT p t = ForallT_ p t
class p (t (SkolemT1 p t) (SkolemT2 p t)) =>
      ForallT_ (p :: k3 -> Constraint) (t :: k1 -> k2 -> k3)
instance p (t (SkolemT1 p t) (SkolemT2 p t)) =>
         ForallT_ (p :: k3 -> Constraint) (t :: k1 -> k2 -> k3)

-- | instantiate a quantified constraint
inst :: forall p a. Forall p :- p a
inst = trans (unsafeCoerceConstraint :: p (Skolem p) :- p a) (Sub Dict)

instF :: forall p f a. ForallF p f :- p (f a)
instF = trans (unsafeCoerceConstraint :: p (f (SkolemF p f)) :- p (f a)) (Sub Dict)

-- | instantiate a quantified constraint on kind @* -> *@
inst1 :: forall (p :: (* -> *) -> Constraint) (f :: * -> *). Forall1 p :- p f
inst1 = inst

instT :: forall (p :: k3 -> Constraint) (t :: k1 -> k2 -> k3) (f :: k1) (a :: k2) .
         ForallT p t :- p (t f a)
instT = trans (unsafeCoerceConstraint :: p (t (SkolemT1 p t) (SkolemT2 p t)) :- p (t f a))
              (Sub Dict)
```

**Comment by oerjan** [comment]
FWIW I'm in the process of trying to write up a version suitable for a pull request.

**Comment by treeowl** [comment]
By the way, I noticed that the code above optimizes beautifully, but with `-O0` produces pretty ugly core. I don't know if there's a way to avoid that without digging into the `Magic`.

**Comment by oerjan** [comment]
BTW I think merging `SkolemF` and `SkolemT1` or `SkolemT2` *could* be a bad idea, as the kinds used can unify:

```
SkolemF vs. SkolemT1
k2 = k3'
k1 = k1'
k2 = k2' -> k3' = k2' -> k2

SkolemF vs. SkolemT2
k2 = k3'
k1 = k1'
k1 = k2'
k2 = k2' -> k3' = k1 -> k2
```

Of course these kinds would be infinite, and so normally disallowed. But since types and kinds will be merged in GHC 8.0, and there's already a known way (using type families, naturally) of tricking GHC into accepting essentially infinite types, this could in theory break the principle that unrelated `Forall*` calls should not use the same Skolem. (This doesn't mean it can *actually* be abused, mind you.)

**Comment by treeowl** [comment]
Do you have a link to an example of this horrifying trick? I don't see how such unification could be exploited (SkolemT1 does not unify with SkolemT2, etc.), but as you said we don't gain anything obvious from that generalization anyway. With your new class version of `Forall`, my extra-polykinded `Forall` stops making sense too, so forget it!

**Comment by oerjan** [comment]
I think [GHC ticket #8162](https://ghc.haskell.org/trac/ghc/ticket/8162) is where I saw it. As far as I understand, it was the reason for inventing the "surely apart" requirement on type family parameters (basically, type family instance overlap must be rejected even if the overlap requires infinite types.)

The parameters of `SkolemT1` and `SkolemT2` definitely *do* unify, and finitely so, those *must* be kept separate - identifying them basically means that the two test parameters for `t` become *equal* if they are of the same kind. If `SkolemT1 = SkolemT2`, then the following works:

```
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE ConstraintKinds #-}
{-# LANGUAGE UndecidableInstances #-}

import Data.Constraint
import Data.Constraint.Forall -- version adjusted to make SkolemT1 = SkolemT2

class a => Id a
instance a => Id a

uc :: forall a b. a -> b
uc = case instT of
    Sub (Dict :: Dict (Id (a ~ b))) -> id
```

**Comment by oerjan** [comment]
Pull request sent! (My first, yay!)
