### ISSUE TITLE
Data.Constraint.Nat Log2 functions

### ISSUE THREAD

**Issue by phadej** [ekmett/constraints#126]

**Comment by RyanGlScott** [comment]
What sort of functions do you have in mind?

Writing laws for `Log2` is tricky due to the fact that `Log2` rounds down its result to the nearest integer, so many of the usual laws about logarithms don't apply to `Log2`. For instance, there is the logarithm product rule:

$log_b(x \times y) = log_b(x) + log_b(y)$

This rule doesn't hold for `Log2`, however. A counterexample is when $`x = y = 3`$:

```
λ> :kind! Log2 (3 * 3)
Log2 (3 * 3) :: Natural
= 3
λ> :kind! Log2 3 + Log2 3
Log2 3 + Log2 3 :: Natural
= 2
```

**Comment by phadej** [comment]
At least `forall n m. (1 <= n, KnownNat n) :- KnownNat (Log2 n)`

There's one equality: `Log2 (Pow 2 n) ~ n`

We could have `Log n + Log m <= Log2 (n * m)`, `1 <= n`, `1 <= m`;  `(2 ^ Log2 n) <= n` etc inequalities; but I not sure about these.

The `:-` is however good to have for consistency.

**Comment by RyanGlScott** [comment]
I've opted to only add `KnownNat (Log2 n)` and `Dict (Log2 (2 ^ n) ~ n)` for now. See #127.
