### ISSUE TITLE
Forall interface

### ISSUE THREAD

**Issue by treeowl** [ekmett/constraints#18]
The fact that `Forall` is (still) a type family is a bit annoying for two reasons: users are required to enable `TypeFamilies`, and `Forall` itself is not first class. Would it be possible to wrap it up with one more class to fix that, or would that bring back the cycle errors?

Mostly unrelatedly, the next major version of the package should, IMO, deprecate the now-redundant `Forall1` and `inst1`. Is there a good place to make a note of that?

**Comment by oerjan** [comment]
Actually, users *don't* need to enable `TypeFamilies`, I just checked. I did have the idea that maybe `Forall` etc. should be made point-free, though. I've not made a commit because it depends on whether the `ForallT` is accepted or not.

Also, the kind subtlety with `ForallT` has made me wonder if maybe `Forall1` should be kept around (although slightly generalized in kind) for the same reason.

**Comment by oerjan** [comment]
By the way I don't *think* it would bring back the cycle errors, but once they're made point-free I'm not sure there's enough of a difference to justify adding a third level... also the new `ForallV` I proposed generalizes `Forall` and has the class outermost for several reasons.

**Comment by oerjan** [comment]
Actually I was wrong, it *does* bring back cycle errors. On testing, it seems that *sometimes* type families get expanded in superclasses (which also explains why putting the class outside the type family didn't work, I didn't think about that clearly enough.)

I am completely confused now about the rules for when expansion happens or not... which leaves me with the worry that someone might fix GHC to make it consistent at some point, breaking this module if the wrong decision is made.

One possibility I'm thinking of is that maybe the `Forall*_` classes should *also* be exported - that way, users can have access to these to use as class and type family head arguments if needed, at the cost of somewhat higher risk (I assume) of superclass cycles.

Also, as I should have expected, `ForallV` also gives cycle errors if you try to nest it. (Although it's *intended* to make nesting redundant.) Adding an outside type family to that seems to fix it - it's not enough to use the original one outermost as that ruins instance selection for `InstV`: `p` is not determined from the type of `instV` unless `Forall` is injective. I didn't do that initially because I thought non-injectivity would break even an extra outer one, but it seems to work by expansion.

I think I'll add that to the open pull request, after a bit of experimenting to see if one type family can be made to work instead.

On the bright side:

1. Making the type families point-free seemed to have no ill effect. Although I should check if that is a recent GHC feature...
2. `ForallF` seems to work nicely with point-free nesting.

**Comment by treeowl** [comment]
I wonder if you might be able to come up with a sensible rule the GHC gurus would accept. Referencing #17 to link these things.

**Comment by Icelandjack** [comment]
Removing `theDefer` / `theDeferEither` wasn't mentioned in the change log, was it intentional?

**Comment by ekmett** [comment]
When I went to do the merge they weren't being exported from the module, weren't used internally, and had a type error, so I dropped them.

**Comment by ekmett** [comment]
I'm not against taking a patch that adds them back.

**Comment by ekmett** [comment]
Maybe as `defer_` and `deferEither_` ? That fits closer with similar naming schemes I use elsewhere

**Comment by ekmett** [comment]
(I wasn't able to compile them as written with GHC 8.0.1.)
