### ISSUE TITLE
constraints-core

### ISSUE THREAD

**Issue by andrewthad** [ekmett/constraints#19]
Version 0.6 added a lot of dependencies, all of which (I think) are used for instances that `Lifting` has. Would you be amenable to the idea of moving `Data.Constraint` to a separate package (`constraints-core` or something like that) with fewer dependencies (since that module seems to be stable at the point and doesn't need any typeclass instances).

**Comment by ekmett** [comment]
Not everything is for `Lifting`: `Class` and `(:=>)` are huge orphan magnets as well, and were originally only implemented for `base` instances, but the core libraries generally can't incur any new dependencies like this going the other way around.

I'm rather inclined to leave things together, as I intend to go through and properly add the missing `Class` and `(:=>)` instances for the packages this package depends on. (I should have done so long ago, but haven't had the energy to tackle it.) 

In a split story those instances would be forced to be orphans, and I pretty flatly refuse to maintain packages full of orphans as they induce terrible failure modes for users.

This is aside from pragmatic concern that I get a lot of 'please lift out this particular small core or that one out of package XYZ' requests at the same time a I get requests to add instances for X Y or Z that would otherwise be orphaned. These requests can rarely agree on what the small core should be. The problem with them is their net effect is to pretty much render my life as a maintainer a living hell, as I often have to deal with release cascades of 40+ package releases when I move content between packages that sit under a bunch of others like this. If at any point we cleave wrongly and I have to move stuff between the two packages later, that can eat a week at a time and increase trustee work.

Given the "new" dependencies here are all actually core libraries except `hashable`, which is all but morally one, and `transformers-compat` -- which sees wide adoption for patching over the incompatible changes we get in `transformers` -- and the orphan instance issue for said core libraries I'm going to lean towards not doing this at this time. 

I'm far more inclined in the medium-to-long term to see about getting the core `Data.Constraint` module into `base`, (possibly modulo Class and (:=>), depending on standardization woes) but the story of how to juggle where the instances wind up while avoiding orphans is a rather headache inducing affair on the best day. It'd be a slightly more desirable state to reach as it'd let us simultaneously extend things correctly to all the core libraries, but the transition/coordination pain to get there is something I'm not in a hurry to endure, and would last multiple years. I'm already living through it in miniature with the migration of `Semigroup` into `base`, and that is far, far less exotic!

Tentatively closing this to signal intent.

**Comment by andrewthad** [comment]
I appreciate the explanation. That makes a lot of sense (especially the orphan problem). Fortunately, I no longer even need such a `constraints-core`.
