### ISSUE TITLE
License mismatch between Cabal and LICENSE file

### ISSUE THREAD

**Issue by peti** [ekmett/constraints#35]
The Cabal file places this code under BSD3 but the LICENSE file contains a BSD2 license.

**Comment by oerjan** [comment]
Sheesh. In case this matters, I hereby grant either license for the parts I contributed.

**Comment by ekmett** [comment]
I explicitly use a BSD2 license, but older cabal versions don't let me state that. You are free to add the extra clause if you need. This holds across all of my packages and is considered wontfix at this time, as any "fix" requires me to shut down a whole bunch of GHC releases.

**Comment by oerjan** [comment]
I'd imagine the relevant question is whether you're legally in the clear to use our contributions as BSD2, when this ambiguity is there.

**Comment by ekmett** [comment]
Well, every single files says `BSD-style (see the file LICENSE)` not `BSD3`.

The only thing that says BSD3 anywhere is metadata used by cabal.

**Comment by ekmett** [comment]
So the source files and the license file all agree.

**Comment by ekmett** [comment]
The only thing that "lies" is the license metadata field provided to cabal, which is a statement of permission to downstream libraries. Historically there was no `OtherLicense` option, and the field has always parsed as a conservative upper bound on the license by defaulting to `AllRightsReserved`, so I do the only thing our relatively crappy metadata allows.

**Comment by peti** [comment]
The incorrect Cabal tag is problematic mostly for distributors who use the meta information from the Cabal file to include licensing information in the packages they distribute. I.e. packages distributed by NixOS, openSUSE Linux, and others will advertise their constraints package as being distributed under the BSD3 license, when it fact it's not.

**Comment by ekmett** [comment]
Users are free to use any BSD2 package under BSD3, the latter merely adds a clause, so is a strict subset of the permissions granted by the license file.

I'm simply giving a more permissive license in the text, because I can go this direction, but not the reverse. If the metadata situation were reversed, _then_ there'd be a problem. As it is there is no difference to any other sort of situation that arises when you can provide the same code under multiple licenses.

If someone wanted to use this fact and send me patches restricted under BSD3, I'd have to choose whether to keep the existing BSD2 license or accept their patches. 

This is exactly the same situation that arises when folks use LGPL with a linking exception. Most (all?) package managers don't track the extra clause which grants extra permissions to the user. Here BSD2 is BSD3 minus a clause, having the same effect.

**Comment by peti** [comment]
> I'm simply giving a more permissive license in the text, because I can go this direction, but not the reverse.

This is all true and I understand your reasoning. Still, the openSUSE lawyers don't care about these distinctions. Our guidelines say that the spec file must give proper licensing information, and the licensing information generated by `cabal-rpm` is not (and cannot be) correct. Which kinda sucks. I don't see any obvious solution for this dilemma. Supporting old Cabal versions is a good idea, obviously, but it does make life harder for other people, too.

**Comment by ekmett** [comment]
I'll grudgingly accept a patch to each package I maintain that switches the license to BSD3, but I personally think the situation is bullshit.

**Comment by ekmett** [comment]
Actually. For this package, I suppose I can switch the metadata, as `constraints` doesn't work on older GHCs.
